DECLARE SET INT @CODIGO_CLIENTE = 0;
DECLARE SET INT @DATA_EMISSAO = 0;
DECLARE SET DECIMAL @VALORFINAL = 0;

CREATE
or replace VIEW  VW_VALIDA_DUP_PEDIDO AS
SELECT
    VDPEDCPP_PRE_PED
FROM
     VDPEDCPP
WHERE
    VDPEDCPP_CODCLI = @CODIGO_CLIENTE
    AND VDPEDCPP_DTEMI = @DATA_EMISSAO
    AND VDPEDCPP_VLRFIN = @VALORFINAL;